examples/memory.py
justfile
src/instance.rs
src/lib.rs
src/memory_view.rs
tests/instance.py
tests/memory_view.py

This patch does 2 things:
1. Add more memory view types (with `uint8`, `int8`, `uint16`, `int16`, `uint32` and `int32`),
2. Check whether get and set are inside the range of the memory size.

feat(extension) More memory view types, and better errors

---

README.md
examples/memory.py
src/memory_view.rs
tests/memory_view.py

This patch does the following:
* Replace `length` by `__len__`,
* Replace `get` by `__getitem__`,
* Replace `set` by `__setitem__`.
The result feels more Python. Before:
```python
while (0 != memory.get(nth)):
string += chr(memory.get(nth))
nth += 1
…
memory.length()
```
After:
```python
while (0 != memory[nth]):
string += chr(memory[nth])
nth += 1
…
len(memory)
```

feat(extension) Better Python API for `*MemoryView`

---

README.md
examples/memory.py
src/memory/view.rs
tests/test_memory.py

WIP
* `memory[7]` reads 1 cell of the memory at offset + 7,
* `memory[7:13]` reads 6 cells of the memory at offset + 7.

feat(extension) Support slices as indices for `Memory.__getitem__`

---

Cargo.lock
Cargo.toml

Fix #20.
This patch updates Wasmer to 0.4.0. It also updates other dependencies.

chore(dependencies) Update Wasmer to 0.4.0

---

src/lib.rs
tests/test_instance.py

It is useful to access the version string of the Python package (same as the crate) from Python, for example:
```
>>> import wasmer
>>> wasmer.__version__
'0.2.0'
```
Added a test.
I will be glad to make the entire module more pythonic if it can help, adding more useful magic methods.

feat(extension) Implement `__version__` for module

---

src/instance.rs

Hope you are ok with adding the documentation this way, it has been really useful to me to connect the dots between Python, `pyo3`, `wasmerio` and WebAssembly specs.
Other points:
* I have noticed that naming `struct ExportedFunctions` can be really confusing and, as far as I understood, what you want to achieve is to give access to a Python namespace (that is how Python calls modules, sub-packages, functions scopes, etc.). So I would suggest to rename <s>`ExportedFunctions`</s> to `Namespace`.
* the use of `__repr__` is not right imo, as for that use-case `__str__` should be used. `__repr__` should return not a string, but something that could be evaluated via `eval`, see [doc](https://docs.python.org/3/reference/datamodel.html#object.__repr__). 
Let me know what you think. I can create …

Add documentation to instance.rs

---

README.md
src/instance.rs
src/lib.rs
src/module.rs
tests/test_instance.py
tests/test_module.py

The `Module` class provides:
1. `__init__` to compile a sequence of bytes into a WebAssembly module,
2. `instantiate` to instantiate a module (and get an `Instance` object),
3. `validate` —a static method— to check whether the given bytes represent a valid WebAssembly module.

feat(module) Introduce the `Module` class

---

README.md
src/module.rs
tests/test_module.py

These patches allow to serialize and deserialized a compiled WebAssembly module, thus saving the compilation time for the next use.
Example:
```python
from wasmer import Module
wasm_bytes = open('my_program.wasm', 'rb').read()
module1 = Module(wasm_bytes)
serialized_module = module1.serialize()
del module1
module2 = Module.deserialize(serialized_module)
result = module2.instantiate().exports.sum(1, 2)
print(result) # 3
```

feat(module) Implement `Module.serialize` and `Module.deserialize`

---

Cargo.toml
build.rs
src/lib.rs
tests/test_instance.py

Fix #41.
The `__core_version__` constant is set to the version of the
`wasmer-runtime-core` Rust package, aka the core runtime.
Thoughts @Mec-iS?
To test:
```python
import wasmer
print(wasmer.__core__version__)
```

feat(extension) Add `wasmer.__core_version__`

---

src/memory/view.rs

When writing `memory_view[0:]`, an error could be raised because the
default Python bound for a slice with no upper bound is likely to be
larger than the memory size. Instead of getting an error, this patch
bounds the slice upper bound to the memory size.

feat(memory) Bound slice to the size of the memory view

---

README.md
src/memory/mod.rs
tests/test_memory.py

This method can be used to grow the memory by a number of pages (65kb each).

feat(memory) Add the `Memory.grow` method

---

Cargo.lock
Cargo.toml

This PR updates all dependencies and the runtime to 0.5.5.

chore(runtime) Update Wasmer to 0.5.5

---

benchmarks/test_memory_view_set.py
benchmarks/test_nbody.py
examples/greet.py
justfile
src/memory/view.rs
tests/test_memory.py

When writing `view = memory.uint8_view()` for instance, it is now
possible to set a sequence directly by writing:
```python
view[start:stop:step] = sequence
```
instead of writing a loop like:
```python
for nth in range(0, length):
view[nth] = sequence[nth]
```
First, `__setitem__` takes 2 forms of inputs: Either the key and value
are both integers, or they are respectively a slice and a sequence. By
“sequence”, we mean the [object protocol
sequence](docs.python.org/3/c-api/sequence.html), so it
includes list, bytes, bytearray etc.
Second, let's focus on the new feature where key and value are a slice
and a sequence:
- The sequence item type must be down-castable to the memory item
type, e.g.  if it is a `uint8` view, then the item must be
down-castable to `u8`, and so on.
- The slice is …

feat(memory) Memory views support slice assignment

---

.circleci/config.yml
.gitignore
Cargo.lock
Cargo.toml
justfile
wasmer-any/setup.py
wasmer-any/wasmer/__init__.py

Python wasmer installation is failing in various systems (mainly because of alpine linux).
https://github.com/syrusakbary/snapshottest/issues/88
https://github.com/syrusakbary/fastdiff/issues/2
https://github.com/syrusakbary/fastdiff/issues/3
One way to make it work very easily is by creating a generic wheel that it's always available but that fails on import (rather than on install).
This PR adds that, and upgrades wasmer to `0.5.6` as well

Make wasmer silently available anywhere

---

src/instance/exported.rs
src/instance/inspect.rs
src/instance/mod.rs
src/module.rs
tests/test_instance.py

* `InspectExported`: add methods to retrieve signature of `DynFunc`
* Create a `instance` module
* Factorize out `ExportedFunction`
NOTE: substitute #69 
I found these methods very useful when trying to implement [these utilities](https://github.com/Mec-iS/rust-wasm-python-101/blob/50ae7799bb0eeb725a5792dd1e83d258b70e21ae/pywasm/src/utils.py#L9) for leveraging memory views from Python.

Add trait to  allow inspection of exported functions

---

Cargo.lock
Cargo.toml

This patch updates dependencies, including Wasmer 0.10.1.

chore(cargo) Update dependencies, incl. Wasmer 0.10.1

---

src/instance/mod.rs
src/module.rs
tests/test_module.py

This patch implements `Module.exports` to list all the exports with the associated name and kind.

feat(module) Implement the `exports` getter to list exports

---

src/instance/exports.rs
src/lib.rs
src/module.rs
tests/test_module.py

This patch creates a new `ExportKind` int enum defined as:
```python
class ExportKind(IntEnum):
FUNCTION = 1
MEMORY = 2
GLOBAL = 3
TABLE = 4
```
Since pyo3 doesn't have a mapping from Rust to Python enum (cf https://github.com/PyO3/pyo3/issues/417), we had to find a workaround to create it. I believe the approch taken in this PR isn't too ugly. The enum is created with [the functional API](https://docs.python.org/3/library/enum.html#functional-api), such as:
```python
IntEnum("ExportKind", "FUNCTION MEMORY GLOBAL TABLE")
```
Variants order and variant names are defined by implementations on `ExportKind` in Rust.
Then, this new `ExportKind` enum is used in `Module.exports` as values of the `kind` pair.

feat(module) `Module.exports` uses the new `ExportKind` int enum for the `kind` value

---

benchmarks/test_memory_view_get.py
src/lib.rs
src/memory/buffer.rs
src/memory/mod.rs
src/memory/view.rs
tests/test_memory.py

This PR implements the new `Buffer` class. To get one, use the `instance.memory.buffer` getter. This class implements the Python Buffer Protocol. The goal was to test wheter reading operations could be faster, and it actually is, see the benchmark below.
`bytearray(instance.memory.buffer)` is 15x faster than `instance.memory.int8_view()`
`memoryview(instance.memory.buffer)` is 14x faster than `instance.memory.int8_view()`
|Name (time in ns) |                                  Min         |          Max       |          Mean       |        StdDev     |          Median        |       IQR     |      Outliers |OPS (Kops/s) |          Rounds |Iterations|
|------------------------------------------|---------------------:|----------------------:|-------------------:|--------------------:|--------- …

feat(memory) New `Buffer` class, to read memory fast

---

README.md
tests/test_memory.py

Explain the `Buffer` class, recently introduced.

doc(readme) Improve the Memory Section

---

.github/workflows/release.yml

Initially, we stripped the `z` in `x.y.z` in version numbers. Now,
they are represented as `x.y` only, so stripping is no longer
required.

fix(github-actions) Fix the `release` script since version numbers have changed

---

src/instance/mod.rs
tests/test_instance.py

To call a funtion by its index, you just need to do this:
```python
name = instance.resolve_exported_function(index)
getattr(instance.exports, name)(*arguments)
```

feat(instance) Replace `call_function_by_index` by `resolve_exported_function`

---

src/instance/exports.rs
src/instance/inspect.rs
src/lib.rs
src/module.rs
src/type.rs
tests/test_instance.py
tests/test_type.py

This PR updates `ExportedFunction.getfullargspec` to return a  `FullArgSpec` named tupled, as in the `inspect` module strictly.
Thus, it introduces the `Type` int enum.
It also updates the `ExportImportKind` int enum to implement the `ToPyObject` trait.
The `ExportedFunction.getargs` function has been removed, since it no longer makes sense.

feat(instance) `ExportedFunction.getfullargspec` returns a `FullArgSpec` named tuple

---

.github/workflows/release.yml
justfile
wasmer-any/setup.py

Fix #151.
Since we have moved from `pyo3` to `maturin` to publish the wheels, the `wasmer-any` wheel is no longer published (learn more at #151). I hope this patch will the situation.

fix(ci) Publish the `wasmer-any` wheel automatically

---

Cargo.toml

I noticed in https://pypi.org/project/wasmer/ that some metadata are missing from the package. This patch updates the classifiers and adds project URLs.

feat: Add classifiers and project URLs

---

src/instance/mod.rs
src/memory/mod.rs
src/module.rs
src/value.rs
tests/test_annotations.py

This PR adds `text_signature` annotations to the methods exposed from rust to python and tests for it. How it works see [in the pyo3 docs](https://pyo3.rs/v0.9.2/function.html#making-the-function-signature-available-to-python).
Fixes #157 
The annotations make it possible to inspect the function signature on the python side (with either [`inspect.signature`](https://docs.python.org/3/library/inspect.html#inspect.signature), `.__text_signature__`, or `help`:
```python
from inspect import signature
import wasmer
>>> inspect.signature(wasmer.Value.i32)
<Signature (value)>
>>> wasmer.Instance.resolve_exported_function.__text_signature__
"($self, index)"
>>> help(wasmer.Module.custom_section)
```
- Bug fix (non-breaking change which fixes an issue)
- **New feature** (non-breaking change which …

157 add function text signature

---

Cargo.lock
Cargo.toml
src/import.rs
src/instance/exports.rs
src/instance/mod.rs

Closes #185.
Follow up of #140. 
Good job @kngwyu and @davidhewitt!

fix(import) Fix the `&'static` hack for imported functions

---

.github/workflows/test.yml
justfile

The CI is broken because I've updated the `release` workflow without testing the `test` workflow. This patch fixes that.
Also the `build` recipe in the `justfile` is updated to receive a Rust target for `rustc`.

test(ci) Update according to last changes in the `release` workflow

---

.github/workflows/release.yml
.github/workflows/test.yml
Cargo.lock
Cargo.toml
README.md
rust-toolchain
src/import.rs
src/instance/exports.rs
src/instance/globals.rs
src/instance/mod.rs
src/lib.rs
src/memory/buffer.rs
src/memory/mod.rs
src/memory/view.rs
src/module.rs
tests/test_wat.py

Thanks to Pyo3, it is now possible to stick on Rust stable instead of nightly.
Some `PyClass` aren't sendable yet, but it should be possible in a close future.

feat(pyo3) Update Pyo3 to 0.11.1 and remove Rust nightly!

---

Cargo.lock
docs/api/engine/index.html
docs/api/target/index.html
docs/api/wasmer/index.html
packages/api/src/lib.rs
packages/api/src/target.rs
packages/common/Cargo.toml
packages/common/src/engines.rs
packages/common/src/lib.rs
packages/common/src/store.rs
packages/common/src/target_lexicon.rs
tests/test_target.py

This PR creates a new `wasmer.target` submodule, which provides `Target`, `Triple` and `CpuFeatures` classes. Those are used for cross-compilation. Indeed, now, the `JIT` and the `Native` engine constructors support a second parameter: `target=Target`.
Example of cross-compilation to `x86_64-linux-musl`:
```py
from wasmer import engine, target, Store, Module
from wasmer_compiler_cranelift import Compiler
triple = target.Triple('x86_64-linux-musl')
cpu_features = target.CpuFeatures()
cpu_features.add('sse2')
target_ = target.Target(triple, cpu_features)
engine_ = engine.Native(Compiler, target_)
store = Store(engine_)
module = Module(
store,
"""
(module
(type $sum_t (func (param i32 i32) (result i32)))
(func $sum_f (type $sum_t) (param $x i32) (param $y i32) (result i32)
local.get $x …
```

feat: Create the `wasmer.target` submodule to support cross-compilation

---

.github/workflows/release.yml
.github/workflows/test.yml
Cargo.lock
packages/api/Cargo.toml
packages/api/README.md
packages/api/src/store.rs
packages/compiler-cranelift/Cargo.toml
packages/compiler-llvm/Cargo.toml
packages/compiler-singlepass/Cargo.toml

Since October 5th this year, Python 3.9 has been released (https://pythoninsider.blogspot.com/2020/10/python-390-is-now-available-and-you-can.html).
This patch updates the project to target Python 3.9.0.
Python 3.5.0 is kept for backward compatibility for the moment, despites it's been deprecated (https://pythoninsider.blogspot.com/2020/10/python-35-is-no-longer-supported.html).
Fixes https://github.com/wasmerio/wasmer-python/issues/407.

chore: Support Python 3.9

---

Cargo.lock
packages/api/src/externals/function.rs

Closures as host functions are going to be disabled for a moment in
Wasmer, see https://github.com/wasmerio/wasmer/pull/1841. In the
`wasmer` Python package, we were passing a closure to
`Function::new_with_env`. In order to get a regular function, this
patch stores the previously captured varibles into the function
environment. The only concerned variable is `result_types`.

feat(api) Avoid using a closure to declare host function

---

.gitignore
conftest.py
packages/api/src/externals/global.rs
packages/api/src/externals/memory.rs
packages/api/src/import_object.rs
packages/api/src/lib.rs
packages/api/src/memory/buffer.rs
packages/api/src/types.rs
tests/test_docs.py

As discussed in #223, I think testing the documentation requires a custom plugin. At the moment it's very rough around the edges in particular when it comes to error reporting. 
When I run the current state, I already get the following errors:
```
FAILED tests/test_docs.py::test_docexample[docexample2] - NameError: name 'wasm2wat' is not defined
FAILED tests/test_docs.py::test_docexample[docexample8] -   File "foo", line 6
FAILED tests/test_docs.py::test_docexample[docexample15] - NameError: name 'Module' is not defined
FAILED tests/test_docs.py::test_docexample[docexample17] - AssertionError
FAILED tests/test_docs.py::test_docexample[docexample20] - AssertionError
FAILED tests/test_docs.py::test_docexample[docexample25] - NameError: name 'Store' is not defined
FAILED …
```

Initial doctest impl

---

docs/api/wasmer/index.html
packages/api/src/exports.rs
packages/api/src/lib.rs
tests/test_instance.py

This patch updates `Exports` to implement `PyIterProtocol`, aka [the Iterator Protocol](https://docs.python.org/3/c-api/iter.html):
* `Exports.__iter__` returns a new instance of `ExportsIterator`. Due to iterator lifetimes on the Rust side, we have no choice than cloning the content of `Exports`, but it's rather cheap,
* `ExportsIterator.__iter__` returns itself (in case a user calls `iter(instance.exports)` by mistake in a `loop`, which is redundant),
* `ExportsIterator.__next__` returns a pair `(name, export)` if the end of the iterator isn't reached.
Fixes https://github.com/wasmerio/wasmer-python/issues/535.

feat(api) `Exports` implements `PyIterProtocol`

---

docs/api/wasmer/index.html
packages/api/src/externals/function.rs
tests/test_function.py

When a host function has the type-hint `None` for its result, we
consider it's equivalent to nothing:
```python
def foo() -> None:
pass
```
is equivalent to:
```python
def foo():
pass
```
Fixes https://github.com/wasmerio/wasmer-python/issues/534.
Fixes https://github.com/wasmerio/wasmer-python/issues/452.

feat(api) Allow a host function to type-hint the result with `None`

---

packages/api/src/values.rs

Currently passing `0x80000000` into a `i32` parameter generates an overflow error.

Fix conversion of u32 and u64 values into Wasm types

---

packages/api/src/import_object.rs
packages/api/src/instance.rs
packages/api/src/wasi.rs
tests/test_wasi.py

This PR depends on this:
https://github.com/wasmerio/wasmer/pull/2726

WASI imports should return a dict

---

packages/api/src/memory/views.rs
tests/test_memory.py

- Empty slices (`[7:7]`) don't throw an exception any more and are simply a no-op.
- `__getitem__` supports steps.
- Unified the bounds-checking logic between `__getitem__` and `__setitem__`.
- Single-element slices now return a single-element list instead of a scalar value.

 Improve indexing for memory views 

---

justfile
packages/api/README.md

##What
- Add specific version to maturin dep
- Call out that LLVM 12.0 is required to build all compilers
maturin broke their command-line options with v0.13 ([see changelog](https://github.com/PyO3/maturin/blob/main/Changelog.md#0130---2022-07-09)), preventing `just build api` from working.
I've tried at first to install LLVM 12.0.1 using llvmenv, but there were some missing headers in Ubuntu :shrug: Using llvm.sh was the best option to getting everything at once. I've also had to set the `LLVM_SYS_120_PREFIX` env variable to `$(llvm-config-12 --prefix)`
2 tests failed citing the lack of `clang`, is this a required component for further development?
```none
FAILED tests/test_docs.py::test_doctest[<module 'target'>0] - pyo3_runtime.PanicException: Need at least one of `clang-11`, …
```

Small tweak and documentation to build wasmer-python

---

.github/workflows/release.yml
.github/workflows/test.yml
justfile
packages/api/Cargo.toml
packages/api/pyproject.toml
packages/compiler-cranelift/Cargo.toml
packages/compiler-cranelift/pyproject.toml
packages/compiler-llvm/Cargo.toml
packages/compiler-llvm/pyproject.toml
packages/compiler-singlepass/Cargo.toml
packages/compiler-singlepass/pyproject.toml

This PR is to make wasmer-python run with support for python 3.11
- Adds support for python 3.11 (#696)
- Add support for python 3.10 (#680)
- Moves to latest version of maturin (0.14.17) to fix failing windows builds (#715)
I also wanted to get wasmer-python working on M1 as well, but could not get llvm to compile. That should probably be a separate PR anyway since this one is fixing too many things already.

Support for python 3.11
