README.md
This patch presents the `*MemoryView` classes in the `README.md`.
=> doc(readme) Present memory views

src/value.rs, tests/value.py
Yup, I discover Python, don't judge me!
=> feat(extension) Replace `Value.to_string` by `Value.__repr__`

README.md, src/memory_view.rs, tests/memory_view.py
This patch adds the number of bytes per element on all `MemoryView` classes.
=> feat(extension Add `MemoryView.BYTES_PER_ELEMENT`

Cargo.lock, Cargo.toml
=> chore(release) Bump version

README.md
=> doc(readme) Add missing link to the license

.circleci/config.yml, bors.toml
ping @syrusakbary, you might have received a request to install Bors on this repo.
=> chore(ci) Set up Bors

Cargo.lock, Cargo.toml
=> chore(runtime) Update Wasmer to 0.4.1

README.md, examples/greet.py, examples/memory.py
`while True` isn't super secure. It's better to set a limit :-).
=> doc(examples,readme) More Python idiomatic examples

Cargo.lock, Cargo.toml, src/memory/view.rs
Wasmer is updated to 0.8.0.
Pyo3 is also updated to 0.8.0.
=> feat(runtime) Update Wasmer and Pyo3 to 0.8.0

Cargo.lock, Cargo.toml
Fix #91, #92 
This patch updates Wasmer to 0.11.
=> feat(runtime) Update Wasmer to 0.11

.github/workflows/lint.yml, bors.toml, src/instance/exports.rs, src/instance/mod.rs, src/memory/view.rs, src/module.rs
This PR introduces the `lint` Github Actions, and fixes Clippy issues.
=> feat: Lint with Clippy

Cargo.lock, Cargo.toml
Also, update other dependencies.
=> feat(runtime) Update Wasmer to 0.14

.github/workflows/release.yml, .github/workflows/test.yml, bors.toml, justfile, src/memory/view.rs, tests/test_module.py
Address #29 
Windows support is coming…
=> test(ci) Test on Windows

Cargo.lock, Cargo.toml, src/instance/exports.rs, src/instance/mod.rs, src/module.rs, tests/test_instance.py
It depends on https://github.com/wasmerio/wasmer/pull/1306.
As is, it can be merged with my current fork of Wasmer. cc @syrusakbary, thoughts?
=> feat(instance) Introduce `Instance.call_function_by_index`

Cargo.lock, Cargo.toml, src/instance/exports.rs, src/instance/globals.rs, src/instance/mod.rs, src/memory/buffer.rs, src/module.rs, src/value.rs
This PR updates the project to Pyo3 0.9, which includes some breaking changes, and many improvements.
Closes #150 
Closes #152
=> feat(extension) Update to Pyo3 0.9

Cargo.lock, Cargo.toml, README.md, src/lib.rs, tests/test_wat.py
=> feat(wat) Add `wat2wasm` and `wasm2wat` functions

README.md
Fix #206.
Thanks @kk49 for pointing it!
=> doc(readme) Fix a typo.

Cargo.lock, packages/api/Cargo.toml, packages/api/src/exports.rs, packages/api/src/externals/function.rs, packages/api/src/externals/global.rs, packages/api/src/externals/memory.rs, packages/api/src/externals/table.rs, packages/api/src/import_object.rs, packages/api/src/instance.rs, packages/api/src/memory/buffer.rs, packages/api/src/memory/views.rs, packages/api/src/module.rs, packages/api/src/store.rs, packages/api/src/types.rs, packages/api/src/wasi.rs, packages/api/src/wat.rs, packages/compiler-cranelift/Cargo.toml, packages/compiler-llvm/Cargo.toml, packages/compiler-singlepass/Cargo.toml, packages/engines/Cargo.toml, packages/engines/src/engines.rs, packages/engines/src/target_lexicon.rs, tests/test_module.py
This patch updates Wasmer from `master` branch to 1.0.0-alpha4, and updates Pyo3 from 0.11 to 0.12.
=> chore: Update Wasmer and Pyo3

Cargo.lock, packages/api/Cargo.toml, packages/compiler-cranelift/Cargo.toml, packages/compiler-llvm/Cargo.toml, packages/compiler-singlepass/Cargo.toml, packages/engines/Cargo.toml
=> chore: Update dependencies

.github/workflows/release.yml, .github/workflows/test.yml, justfile, scripts/update-version.sh
=> Write the (pre)release workflow

Cargo.lock, packages/api/Cargo.toml, packages/api/src/externals/function.rs, packages/compiler-cranelift/Cargo.toml, packages/compiler-llvm/Cargo.toml, packages/compiler-singlepass/Cargo.toml, packages/engines/Cargo.toml, packages/engines/src/engines.rs
Close #441.
This PR updates Wasmer to 1.0.0-beta2.
=> chore: Update to Wasmer 1.0.0-beta2

.github/workflows/test.yml, tests/test_store.py
We will wait for #423 to land for  that.
=> chore: Do not build compiler-llvm on Windows

packages/api/src/externals/function.rs
By writing `.map(to_wasm_value)`, we need the types (`Vec<Type>`) to
be owned. The types need to be cloned before the `map` in this
particular context, because they are behind a shared reference.
To avoid cloning the entire `Vec<Type>` everytime a host function is
called (either by the host or by Wasm), we change the `map` to
`.map(|(value, type)| to_wasm_value((value, *ty)))`, which simply
_copy_ the `Type`; thus removing the need to clone `Vec<Type>`, we
keep working on a reference to it.
=> feat(api) Avoid cloning `Vec<Type>` for each host function call

packages/api/src/memory/views.rs, tests/test_memory.py
Fix memory views length. Fix #570
=> Fix memory views length. Fix #570

bors.toml, packages/api/src/errors.rs, packages/api/src/externals/function.rs, packages/api/src/instance.rs, tests/test_function.py
Depends on https://github.com/wasmerio/wasmer/pull/2728
=> Propagate python exceptions through Wasm

CHANGELOG.md, Cargo.lock, packages/any-api/setup.py, packages/any-compiler-cranelift/setup.py, packages/any-compiler-llvm/setup.py, packages/any-compiler-singlepass/setup.py, packages/api/Cargo.toml, packages/compiler-cranelift/Cargo.toml, packages/compiler-llvm/Cargo.toml, packages/compiler-singlepass/Cargo.toml, packages/engines/Cargo.toml, scripts/update-version.sh
This PR is to prepare the 1.2.0 release of wasmer-python. Check the changelog committed in this PR for details.
=> Prepare the 1.2.0 release
